### ISSUE TITLE
正则中的(\\s)*，改成(\\s)+，是不是更加合理呢？

### ISSUE THREAD

**Issue by pm123** [JimFirst/postcss-change-css-prefix#1]
`.el-form--label-top `针对这个类名进行替换时，会把lab**el-t**op中的el-也替换掉

**Comment by JimFirst** [comment]
感谢提出的bug，正则中的(\\s)*是不能改成(\\s)+的，因为css选择器会有.el-button.el-tag这种情况，后续我看一下如何修改以解决这个问题

**Comment by JimFirst** [comment]
> 感谢提出的bug，正则中的(\s)*是不能改成(\s)+的，因为css选择器会有.el-button.el-tag这种情况，后续我看一下如何修改以解决这个问题

**Comment by JimFirst** [comment]
v1.0.1已修复

**Comment by pm123** [comment]
好的，感谢
