### ISSUE TITLE
请问这个在vue-cli4的项目中该怎么用 ?

### ISSUE THREAD

**Issue by a15218378694** [JimFirst/postcss-change-css-prefix#2]
希望有个demo, 基于vue-cli4, 或者最新的创建的都行, 谢谢

**Comment by JimFirst** [comment]
> 希望有个demo, 基于vue-cli4, 或者最新的创建的都行, 谢谢

希望你读完readme去尝试一下之后，如果不行，再来提这种问题，既不耽误你时间，也不耽误我时间。
事实上，这个readme都适用vue-cli2、3、4

**Comment by JimFirst** [comment]
> 希望有个demo, 基于vue-cli4, 或者最新的创建的都行, 谢谢

demo地址： https://github.com/JimFirst/change-element-ui-prefix-demo

**Comment by a15218378694** [comment]
> > 希望有个demo, 基于vue-cli4, 或者最新的创建的都行, 谢谢
> 
> 希望你读完readme去尝试一下之后，如果不行，再来提这种问题，既不耽误你时间，也不耽误我时间。 事实上，这个readme都适用vue-cli2、3、4

抱歉, 我昨天用成功了但是没有在这边告知, 但是目前有个新问题, 只有类名改了, 组件没有跟着改, 那组件应该怎么改呢

**Comment by JimFirst** [comment]
> > > 希望有个demo, 基于vue-cli4, 或者最新的创建的都行, 谢谢
> > 
> > 
> > 希望你读完readme去尝试一下之后，如果不行，再来提这种问题，既不耽误你时间，也不耽误我时间。 事实上，这个readme都适用vue-cli2、3、4
> 
> 抱歉, 我昨天用成功了但是没有在这边告知, 但是目前有个新问题, 只有类名改了, 组件没有跟着改, 那组件应该怎么改呢

没看懂你的问题，可以看一下我刚刚上午写的一个简单demo https://github.com/JimFirst/change-element-ui-prefix-demo，理论上，你的项目不需要任何改动，直接引入两个依赖就行。

**Comment by a15218378694** [comment]
vue3 + ts + element-plus最新版本的demo可以给个吗 ? 麻烦了, 实在不知道咋改...

**Comment by a15218378694** [comment]
vue3 + ts + element-plus最新版本的demo可以给个吗 ? 麻烦了, 实在不知道咋改...
