### ISSUE TITLE
vue cli 3.x 用的时候有问题

### ISSUE THREAD

**Issue by 695750180** [JimFirst/postcss-change-css-prefix#3]
![image](https://user-images.githubusercontent.com/18020003/166895071-23503bbb-d960-4602-9ea3-821be180436b.png)
![image](https://user-images.githubusercontent.com/18020003/166895106-25f6a32f-2df8-4160-ae62-10f394b99dec.png)

**Comment by JimFirst** [comment]
> ![image](https://user-images.githubusercontent.com/18020003/166895071-23503bbb-d960-4602-9ea3-821be180436b.png) ![image](https://user-images.githubusercontent.com/18020003/166895106-25f6a32f-2df8-4160-ae62-10f394b99dec.png)

需要在工程根目录新建一个postcss.config.js配置文件，看一下快速上手。具体的可以参考一下https://github.com/JimFirst/change-element-ui-prefix-demo
