### ISSUE TITLE
正则匹配 [class*="el-col-"]

### ISSUE THREAD

**Issue by rfirefly** [JimFirst/postcss-change-css-prefix#4]
[class*="el-col-"] 的规则不能匹配

**解决方案**
reg = new RegExp(`(^|(\\s)+|\\.|=|\\[.*?)${prefix}(?!icon)`, 'g')

**Comment by czbczl** [comment]
使用这个插件其他的都替换了，但是图标相关的el-icon还是会影响全局，这个有办法解决吗
