### ISSUE TITLE
el-icon图标样式污染

### ISSUE THREAD

**Issue by czbczl** [JimFirst/postcss-change-css-prefix#5]
使用这个插件其他的都替换了，但是图标相关的el-icon还是会影响全局，这个有办法解决吗

**Comment by JimFirst** [comment]
> 使用这个插件其他的都替换了，但是图标相关的el-icon还是会影响全局，这个有办法解决吗

这个目前没有办法，因为目前el-icon是字体，不能替换前缀，替换了前缀会找不到图标

**Comment by czbczl** [comment]
> > 使用这个插件其他的都替换了，但是图标相关的el-icon还是会影响全局，这个有办法解决吗
> 
> 这个目标前没有办法，因为目标前el-icon是字体，不能替代前显，替代了前显会找不到图标

好的大佬，这个实际中有其他技巧可以做到图标样式的隔离吗，因为其他主应用有可能对图标样式进行了定制化修改，引入我的组件后el-icon的图标样式影响全局了，这个有其他办法可以弄下吗

**Comment by czbczl** [comment]
> > 使用这个插件其他的都替换了，但是图标相关的el-icon还是会影响全局，这个有办法解决吗
> 
> 这个目标之前没有办法，因为目标之前el-icon是字体，不能替代之前显示，替代了之前显示会找不到图标

好的大佬，这个有其他技巧可以做到图标的样式隔离吗，因为有的应用可能对图标进行了定制化修改，引入我的组件后影响了全局样式，这个有其他方法可以搞定吗

**Comment by czbczl** [comment]
好的大佬，这个有其他技巧可以做到图标的样式隔离吗，因为有的应用可能对图标进行了定制化修改，引入我的组件后影响了全局样式，这个有其他方法可以搞定吗

**Comment by czbczl** [comment]
好的大佬，这个打字怎么发出来就不一样了，这个有其他技巧可以做到图标的样式隔离吗

**Comment by czbczl** [comment]
因为有的应用对图标进行了定制化修改，引入我的组件后图标污染了全局，这个有其他方法可以搞定吗 @JimFirst

**Comment by JimFirst** [comment]
> 因为有的应用对图标进行了定制化修改，引入我的组件后图标污染了全局，这个有其他方法可以搞定吗 @JimFirst

既然你们子应用图标都定制化修改了，为什么不把iconfont的字体名字改成别的名字，不要以el-icon-的形式命名

**Comment by czbczl** [comment]
> > 因为有的应用对图标进行了定制化修改，引入我的组件后图标污染了全局，这个有其他方法可以搞定吗 @JimFirst
> 
> 既然你们子应用图标都定制化修改了，为什么不把iconfont的字体名字改成别的名字，不要以el-icon-的形式命名

是这样的大佬，有的他是直接覆盖的element的样式进行修改的，现在他们需要引入一个我做的组件，但是我的组件中引入了el-icon的样式，import 'element-ui/lib/theme-chalk/icon.css';  这样的话会作用到全局，而且优先级好像会更高，就影响了他们， 这种有什么技巧或者方法可以处理吗

**Comment by czbczl** [comment]
@JimFirst

**Comment by JimFirst** [comment]
> > > 因为有的应用对图标进行了定制化修改，引入我的组件后图标污染了全局，这个有其他方法可以搞定吗 @JimFirst
> > 
> > 
> > 既然你们子应用图标都定制化修改了，为什么不把iconfont的字体名字改成别的名字，不要以el-icon-的形式命名
> 
> 是这样的大佬，有的他是直接覆盖的element的样式进行修改的，现在他们需要引入一个我做的组件，但是我的组件中引入了el-icon的样式，import 'element-ui/lib/theme-chalk/icon.css'; 这样的话会作用到全局，而且优先级好像会更高，就影响了他们， 这种有什么技巧或者方法可以处理吗

没什么办法，这样操作一定会污染
